### PR TITLE
[test] Fix #39 Init test coverage

### LINKED ISSUE #39: [test] Enable test coverage
- [ ] handle multiple package
  - it is handled by go tool in 1.10 https://github.com/golang/go/issues/6909 https://github.com/golang/go/issues/10271
  - before that, might try goveralls https://github.com/mattn/goveralls/issues/20
  - Ayi was using myfork  https://github.com/at15/overalls
- just need to view it online, don't care much about the actual coverage ...

Ref

- https://blog.golang.org/cover

````
go test -coverprofile=c.out ./generator
# will open a browser window and generate a html file in /tmp
go tool cover -html=c.out
````

### PR DESCRIPTION
**Pull request by at15**
- go 1.10 has coverprofile for multiple packages
- [x] go 1.9 might break, if that is the case, I will drop go 1.9 support

### CODE REVIEW

**Comment by gaocegege** [comment]
竟然还没弃坑

**Comment by at15** [comment]
@gaocegege 讲道理 log 和 error 已经吊打很多流行的 package 了 .....

**Comment by at15** [comment]
hmm go1.9.x did failed ... https://travis-ci.org/dyweb/gommon/jobs/374712266

`````
go test -coverprofile=coverage.txt -covermode=atomic ./cast/... ./config/... ./errors/... ./generator/... ./log/... ./noodle/... ./requests/... ./structure/... ./util/...
cannot use test profile flag with multiple packages
`````

**Comment by gaocegege** [comment]
https://github.com/kubeflow/tf-operator/blob/master/.travis.yml#L33

goveralls 了解一下

**Comment by at15** [comment]
@gaocegege 不需要的 ... 直接不测试 1.9 就可以了, 1.10 已经内置了多 package 的支持了

**Pull request merged**
